name: vocal_offline
description: "Application de contrôle vocal hors-ligne."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  vosk_flutter: 0.3.48
  permission_handler: ^11.3.1
  record: ^5.2.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - models/

# On force l'intégralité de l'écosystème Android à s'aligner sur les versions V2 modernes
dependency_overrides:
  permission_handler: ^11.3.1
  permission_handler_android: ^12.0.13
  record_android: ^1.5.2