name: Flutter APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: false

      # Étape d'installation (qui passe grâce à nos overrides)
      - name: Install dependencies
        run: flutter pub get

      # Étape de build avec injection explicite du chemin du SDK Android
      - name: Build APK
        run: flutter build apk --release
        env:
          ANDROID_SDK_ROOT: ${ANDROID_HOME}